local gameobjects = require "main.modules.player"
local rendercam = require "rendercam.rendercam"

function rendercam.follow_lerp_func(curPos, targetPos, dt)
	local target = targetPos
	target.y = curPos.y
	return vmath.lerp(dt * rendercam.follow_lerp_speed, curPos, target)
end

function init(self)
	self.player = gameobjects.get(hash("player"))
	sound.play("#sound")
end

function update(self, dt)
	rendercam.follow(self.player)
end